# Generated by Django 3.1.3 on 2022-03-07 12:45
import datetime
from django.db import migrations

def create_through_relations(apps, schema_editor):
    Playlist = apps.get_model('playlists', 'Playlist')
    PlaylistItem = apps.get_model('playlists', 'PlaylistItem')
    for playlist in Playlist.objects.all():
        for video in playlist.videos.all():
            PlaylistItem(
                playlist=video,
                video=video,
                order=1,
                timestamp=datetime.date.today()
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
