# Generated by Django 3.1.3 on 2022-03-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_auto_20220304_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='video',
        ),
    ]
