# Generated by Django 3.1.3 on 2022-03-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0008_auto_20220307_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Tv Show',
                'verbose_name_plural': 'Tv Shows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
    ]
